# Generated by Django 3.2 on 2021-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuarios'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='codigo',
            field=models.IntegerField(default='', editable=False, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Responsivo'), ('lni-leaf', 'Folha'), ('lni-layers', 'Design')], max_length=20, verbose_name='Icone'),
        ),
    ]
