# Generated by Django 3.2 on 2021-04-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Back-end', 'Backend'), ('Full-stack', 'Fullstack'), ('Mobile', 'Mobile'), ('Front-end', 'Frontend')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='horario',
            field=models.CharField(max_length=20, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Backend'), ('lni-laptop-phone', 'Responsivo'), ('lni-layers', 'Frontend'), ('lni-mobile', 'Mobile')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('CLT', 'Clt'), ('PJ', 'Pessoa_juridica')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-users', 'Usuarios'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-leaf', 'Folha'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Responsivo')], max_length=20, verbose_name='Icone'),
        ),
    ]
