# Generated by Django 3.2 on 2021-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210418_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Full-stack', 'Fullstack'), ('Back-end', 'Backend'), ('Front-end', 'Frontend'), ('Mobile', 'Mobile')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-laptop-phone', 'Responsivo'), ('lni-cog', 'Backend'), ('lni-layers', 'Frontend')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('CLT', 'Clt'), ('PJ', 'Pessoa_juridica'), ('Estagiario', 'estagiario')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('PJ', 'Pessoa juridica'), ('CLT', 'Clt'), ('Analista de Redes', 'Analista_cop'), ('Estagiario', 'estagiario')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-users', 'Usuarios')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Responsivo'), ('lni-leaf', 'Folha')], max_length=20, verbose_name='Icone'),
        ),
    ]
