# Generated by Django 3.2 on 2021-04-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210417_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuarios'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='codigo',
            field=models.IntegerField(verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Responsivo')], max_length=20, verbose_name='Icone'),
        ),
    ]
