# Generated by Django 3.2 on 2021-04-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210418_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='facebook',
            field=models.CharField(default='#', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Front-end', 'Frontend'), ('Full-stack', 'Fullstack'), ('Back-end', 'Backend'), ('Mobile', 'Mobile')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Backend'), ('lni-layers', 'Frontend'), ('lni-laptop-phone', 'Responsivo'), ('lni-mobile', 'Mobile')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('PJ', 'Pessoa_juridica'), ('CLT', 'Clt'), ('Estagio', 'estagio')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('Estagio', 'estagio'), ('CLT', 'Clt'), ('Analista de Redes', 'Analista_cop'), ('PJ', 'Pessoa juridica')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='periodof',
            field=models.DateField(default='Até o momento', verbose_name='Período final'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuarios'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Responsivo'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem')], max_length=20, verbose_name='Icone'),
        ),
    ]
