# Generated by Django 3.2 on 2021-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210418_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='site',
            field=models.CharField(default='#', max_length=100, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Back-end', 'Backend'), ('Front-end', 'Frontend'), ('Full-stack', 'Fullstack')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Responsivo'), ('lni-layers', 'Frontend'), ('lni-cog', 'Backend'), ('lni-mobile', 'Mobile')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('Estagio', 'estagio'), ('PJ', 'Pessoa_juridica'), ('CLT', 'Clt')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('PJ', 'Pessoa juridica'), ('Analista de Redes', 'Analista_cop'), ('CLT', 'Clt'), ('Estagio', 'estagio')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuarios'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-laptop-phone', 'Responsivo'), ('lni-leaf', 'Folha'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete')], max_length=20, verbose_name='Icone'),
        ),
    ]
