# Generated by Django 3.2 on 2021-04-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210417_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologia',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuarios'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Responsivo')], max_length=20, verbose_name='Icone'),
        ),
    ]
