# Generated by Django 3.2 on 2021-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210418_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Full-stack', 'Fullstack'), ('Front-end', 'Frontend'), ('Back-end', 'Backend'), ('Mobile', 'Mobile')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Responsivo'), ('lni-cog', 'Backend'), ('lni-layers', 'Frontend'), ('lni-mobile', 'Mobile')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('PJ', 'Pessoa_juridica'), ('CLT', 'Clt'), ('Estagio', 'estagio')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('Analista de Redes', 'Analista_cop'), ('PJ', 'Pessoa juridica'), ('CLT', 'Clt'), ('Estagio', 'estagio')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='periodof',
            field=models.DateField(blank=True, verbose_name='Período final'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuarios')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Responsivo'), ('lni-leaf', 'Folha'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete')], max_length=20, verbose_name='Icone'),
        ),
    ]
