# Generated by Django 3.2 on 2021-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210418_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Front-end', 'Frontend'), ('Full-stack', 'Fullstack'), ('Mobile', 'Mobile'), ('Back-end', 'Backend')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-cog', 'Backend'), ('lni-laptop-phone', 'Responsivo'), ('lni-layers', 'Frontend')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('Estagio', 'estagio'), ('Analista de Redes', 'Analista_cop'), ('CLT', 'Clt'), ('PJ', 'Pessoa juridica')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='periodof',
            field=models.CharField(blank=True, max_length=20, verbose_name='Período final'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuarios'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Responsivo'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha')], max_length=20, verbose_name='Icone'),
        ),
    ]
