# Generated by Django 3.2 on 2021-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210418_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='twitter',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Full-stack', 'Fullstack'), ('Back-end', 'Backend'), ('Front-end', 'Frontend'), ('Mobile', 'Mobile')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('CLT', 'Clt'), ('Estagio', 'estagio'), ('PJ', 'Pessoa_juridica')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('PJ', 'Pessoa juridica'), ('CLT', 'Clt'), ('Estagio', 'estagio'), ('Analista de Redes', 'Analista_cop')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='periodof',
            field=models.DateField(verbose_name='Período final'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='site',
            field=models.CharField(default='#', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuarios'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Responsivo'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Design')], max_length=20, verbose_name='Icone'),
        ),
    ]
