# Generated by Django 3.2 on 2021-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210418_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('icone', models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-users', 'Usuarios')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Front-end', 'Frontend'), ('Full-stack', 'Fullstack'), ('Back-end', 'Backend')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-laptop-phone', 'Responsivo'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Frontend'), ('lni-cog', 'Backend')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-laptop-phone', 'Responsivo')], max_length=20, verbose_name='Icone'),
        ),
    ]
