# Generated by Django 3.2 on 2021-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210418_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuarios'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Back-end', 'Backend'), ('Front-end', 'Frontend'), ('Mobile', 'Mobile'), ('Full-stack', 'Fullstack')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Backend'), ('lni-layers', 'Frontend'), ('lni-laptop-phone', 'Responsivo'), ('lni-mobile', 'Mobile')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('CLT', 'Clt'), ('Estagio', 'estagio'), ('PJ', 'Pessoa_juridica')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('CLT', 'Clt'), ('Estagio', 'estagio'), ('PJ', 'Pessoa juridica'), ('Analista de Redes', 'Analista_cop')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-leaf', 'Folha'), ('lni-layers', 'Design'), ('lni-github', 'Github'), ('lni-laptop-phone', 'Responsivo'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem')], max_length=20, verbose_name='Icone'),
        ),
    ]
