# Generated by Django 3.2 on 2021-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210418_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='slug',
        ),
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(max_length=120, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='celular',
            field=models.CharField(max_length=13, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.CharField(max_length=250, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-users', 'Usuarios'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Back-end', 'Backend'), ('Front-end', 'Frontend'), ('Full-stack', 'Fullstack'), ('Mobile', 'Mobile')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Frontend'), ('lni-laptop-phone', 'Responsivo'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Backend')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('CLT', 'Clt'), ('PJ', 'Pessoa_juridica'), ('Estagio', 'estagio')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('PJ', 'Pessoa juridica'), ('CLT', 'Clt'), ('Estagio', 'estagio'), ('Analista de Redes', 'Analista_cop')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-github', 'Github'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Responsivo'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha')], max_length=20, verbose_name='Icone'),
        ),
    ]
