# Generated by Django 3.2 on 2021-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210418_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-users', 'Usuarios'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='area',
            field=models.CharField(choices=[('Full-stack', 'Fullstack'), ('Front-end', 'Frontend'), ('Mobile', 'Mobile'), ('Back-end', 'Backend')], max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-cog', 'Backend'), ('lni-layers', 'Frontend'), ('lni-laptop-phone', 'Responsivo')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='expectativa',
            name='modalidade',
            field=models.CharField(choices=[('Estagio', 'estagio'), ('CLT', 'Clt'), ('PJ', 'Pessoa_juridica')], max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='modalidade',
            field=models.CharField(choices=[('Estagio', 'estagio'), ('Analista de Redes', 'Analista_cop'), ('CLT', 'Clt'), ('PJ', 'Pessoa juridica')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Responsivo'), ('lni-github', 'Github')], max_length=20, verbose_name='Icone'),
        ),
    ]
